[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/predict"
  to = "https://api-va5v.onrender.com/generate-questions"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://api-va5v.onrender.com/:splat"
  status = 200
  force = true
