[build]
  command = "pnpm build"
  publish = "dist/"

[build.environment]
  NETLIFY_USE_PNPM = "true"
  NODE_VERSION = "18"

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

## Removed edge function to prevent caching API responses

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache"
