[build]
  command = "npm run build"
  publish = "dist/"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "cors", "multer", "serverless-http", "dotenv"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/proxy"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
