[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  PREDICT_ENDPOINT = "https://api-va5v.onrender.com/generate-questions"
  VITE_PREDICT_ENDPOINT = "/api/predict"

[[redirects]]
  from = "/api/predict"
  to = "/.netlify/functions/proxy"
  status = 200
  force = true

[[redirects]]
  from = "/api/proxy"
  to = "/.netlify/functions/proxy"
  status = 200
  force = true
