[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  PREDICT_ENDPOINT = "https://api-va5v.onrender.com/generate-questions"

[[redirects]]
  from = "/api/predict"
  to = "/.netlify/functions/proxy"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://api-va5v.onrender.com/:splat"
  status = 200
  force = true
